apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: logging
type: Opaque
stringData:
  ELASTIC_USERNAME: elastic
  ELASTIC_PASSWORD: "ChangeMe_Strong@123"
  KIBANA_USERNAME: kibana_system
  KIBANA_PASSWORD: "KibanaSystem_Strong@123"
