apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-svc
  namespace: flask-app
  labels:
    app: python-flask-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: python-flask-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
