apiVersion: v1
kind: Secret
metadata:
  name: elastalert-config
  namespace: logging
type: Opaque
stringData:
  config.yaml: |
    rules_folder: /opt/elastalert/rules
    run_every:
      minutes: 1
    buffer_time:
      minutes: 5
    es_host: elasticsearch-svc.logging.svc.cluster.local
    es_port: 9200
    use_ssl: false
    verify_certs: false
    es_username: elastic
    es_password: ChangeMe_Strong@123
    writeback_index: elastalert_status
    alert_time_limit:
      minutes: 10
  smtp_auth.yaml: |
    user: "YOUR_SMTP_USERNAME"
    password: "YOUR_SMTP_PASSWORD_OR_APP_PASSWORD"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-rules
  namespace: logging
data:
  flask-app-pod-crash.yaml: |
    name: Flask-App Pod CrashLoop Alert
    type: frequency
    index: metricbeat-*
    num_events: 1
    timeframe:
      minutes: 2
    realert:
      minutes: 10
    query_key:
      - kubernetes.event.involved_object.name
      - kubernetes.event.reason
    filter:
      - query:
          query_string:
            query: >
              event.dataset:"kubernetes.event" AND
              kubernetes.namespace:"flask-app" AND
              kubernetes.event.involved_object.kind:"Pod" AND
              kubernetes.event.reason:("BackOff" OR "CrashLoopBackOff" OR "Failed" OR "Killing")

    alert:
      - email

    email:
      - "YOUR_ALERT_RECEIVER_EMAIL@example.com"
    from_addr: "YOUR_FROM_EMAIL@example.com"
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    smtp_ssl: false
    smtp_auth_file: /opt/elastalert/config/smtp_auth.yaml
    email_subject: "[ElastAlert] Pod crash in flask-app"
    alert_text_type: alert_text_only
    alert_text: |
      Pod crash event detected in namespace flask-app.
      Pod: {0}
      Reason: {1}
      Message: {2}
      Time: {3}
    alert_text_args:
      - kubernetes.event.involved_object.name
      - kubernetes.event.reason
      - kubernetes.event.message
      - "@timestamp"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  namespace: logging
  labels:
    app: elastalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      containers:
      - name: elastalert
        image: jertel/elastalert2:2.15.0
        args: ["--config", "/opt/elastalert/config/config.yaml"]
        volumeMounts:
        - name: config
          mountPath: /opt/elastalert/config
          readOnly: true
        - name: rules
          mountPath: /opt/elastalert/rules
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: elastalert-config
      - name: rules
        configMap:
          name: elastalert-rules
